name: test-lab1

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    
    - name: Compile
      run: |
        cd lab1
        mkdir bin
        cd bin
        javac ../src/*.java -d .

    - name: Test
      run: |
        cd lab1
        chmod u+x test/*.sh
        test/test1.sh
